# Generated by Django 4.2.13 on 2024-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIPELINE', models.CharField(max_length=255)),
                ('FOLDER', models.CharField(max_length=255)),
                ('SCRIPT', models.CharField(max_length=255)),
            ],
        ),
    ]
